// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBp6p5x9RcHOlr9Sh0z4hwEITIDlHoS9gE',
    appId: '1:808181323938:web:0fed539643a144746a5ffb',
    messagingSenderId: '808181323938',
    projectId: 'puldapii-app',
    authDomain: 'puldapii-app.firebaseapp.com',
    storageBucket: 'puldapii-app.firebasestorage.app',
    measurementId: 'G-X7JXKVW5F4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvkeGo8pw0BLNQOgGZTCBqkTeM2Z7mAjg',
    appId: '1:808181323938:android:cb0d39d5e71834616a5ffb',
    messagingSenderId: '808181323938',
    projectId: 'puldapii-app',
    storageBucket: 'puldapii-app.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEiHP4ArzyO3SWh6-iAuIT5vC5XMISBAc',
    appId: '1:808181323938:ios:4ebbcc3c1614974e6a5ffb',
    messagingSenderId: '808181323938',
    projectId: 'puldapii-app',
    storageBucket: 'puldapii-app.firebasestorage.app',
    iosBundleId: 'id.or.puldapii.app',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEiHP4ArzyO3SWh6-iAuIT5vC5XMISBAc',
    appId: '1:808181323938:ios:fc1237f29d2a21976a5ffb',
    messagingSenderId: '808181323938',
    projectId: 'puldapii-app',
    storageBucket: 'puldapii-app.firebasestorage.app',
    iosBundleId: 'com.example.puldapii',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBp6p5x9RcHOlr9Sh0z4hwEITIDlHoS9gE',
    appId: '1:808181323938:web:dabb3ce1c94102546a5ffb',
    messagingSenderId: '808181323938',
    projectId: 'puldapii-app',
    authDomain: 'puldapii-app.firebaseapp.com',
    storageBucket: 'puldapii-app.firebasestorage.app',
    measurementId: 'G-HHFTE4C6C5',
  );
}
